DROP TABLE IF EXISTS card_groups;
DROP TABLE IF EXISTS card;
DROP TABLE IF EXISTS groups;

CREATE TABLE card (
  id SERIAL PRIMARY KEY,
  title TEXT UNIQUE NOT NULL,
  content TEXT NOT NULL,
  hint TEXT NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE groups (
  id SERIAL PRIMARY KEY,
  title TEXT UNIQUE NOT NULL,
  description TEXT NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE card_groups (
  card_id INTEGER NOT NULL,
  groups_id INTEGER NOT NULL,
  FOREIGN KEY (card_id) REFERENCES card (id),
  FOREIGN KEY (groups_id) REFERENCES groups (id),
  primary key (card_id, groups_id)
);
